# Nome do workflow
name: Deploy Backend to AWS ECS

# Gatilho
on:
  push:
    branches:
      - master

# Váriaveis de ambiente para o workflow
env:
  AWS_REGION: us-east-2
  ECS_SERVICE: casa-moreno-backend-service
  ECS_CLUSTER: casa-moreno-cluster
  CONTAINER_NAME: casa-moreno-backend-container
  IMAGE_NAME: matteusmoreno/casa-moreno-backend

jobs:
  # Job 1: Builda a imagem Docker e envia para o Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ env.IMAGE_NAME }}:${{ github.sha }} # Usamos um tag único por commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}, ${{ env.IMAGE_NAME }}:latest

  # Job 2: Fazer o deploy no ECS
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download ECS Task Definition
        run: |
          aws ecs describe-task-definition --task-definition casa-moreno-backend-task --query taskDefinition > task-definition.json

      # --- NOVA LINHA DE CORREÇÃO AQUI ---
      - name: Clean task definition for deployment
        run: |
          jq 'del(.enableFaultInjection)' task-definition.json > task-definition-clean.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition-clean.json # Usamos o arquivo limpo
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.build-and-push.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true