name: Docker Deploy to EC2 on master push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto' # Ou 'temurin', 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: matteusmoreno/casa-moreno-backend:latest # Substitua com o nome da sua imagem
          file: ./Dockerfile # Garanta que seu Dockerfile esteja na raiz do projeto

      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          timeout: 600s # Aumentado para 10 minutos para dar tempo para build/pull/run
          script: |
            echo "Parando e removendo container Docker antigo (se existir)..."
            # Parar e remover o container que está usando a imagem 'matteusmoreno/casa-moreno-backend'
            docker ps -q --filter "ancestor=matteusmoreno/casa-moreno-backend" | xargs -r docker stop
            docker ps -aq --filter "ancestor=matteusmoreno/casa-moreno-backend" | xargs -r docker rm
            
            # Opcional: Remover imagens antigas para liberar espaço
            # docker rmi matteusmoreno/casa-moreno-backend:latest || true
            
            echo "Puxando a nova imagem Docker..."
            docker pull matteusmoreno/casa-moreno-backend:latest
            
            echo "Rodando a nova imagem Docker..."
            # Substitua os nomes das variáveis de ambiente e portas conforme sua necessidade
            docker run -d \
              --name casa-moreno-backend-container \
              -p 8085:8085 \
              -e POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              matteusmoreno/casa-moreno-backend:latest
            
            echo "Verificando containers Docker em execução..."
            docker ps -a
            echo "Verificando logs do container recém-criado (pode demorar um pouco para aparecer)..."
            sleep 10
            docker logs casa-moreno-backend-container --tail 50