name: Docker Deploy to EC2 on master push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: matteusmoreno/casa-moreno-backend:latest
          file: ./Dockerfile

      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          timeout: 600s
          script: |
            echo "Parando e removendo container Docker antigo (se existir)..."
            docker ps -q --filter "ancestor=matteusmoreno/casa-moreno-backend" | xargs -r docker stop
            docker ps -aq --filter "ancestor=matteusmoreno/casa-moreno-backend" | xargs -r docker rm
            
            echo "Puxando a nova imagem Docker..."
            docker pull matteusmoreno/casa-moreno-backend:latest

            echo "Criando o arquivo de credenciais do Google Cloud..."
            # --- CORREÇÃO AQUI: Adicionado aspas simples para preservar a formatação do JSON  ---
            echo '${{ secrets.GCP_SA_KEY }}' > /home/ec2-user/gcp-key.json
            
            echo "Rodando a nova imagem Docker..."
            docker run -d \
              --name casa-moreno-backend-container \
              -p 8085:8085 \
              -e POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e EMAIL_GOOGLE_USERNAME=${{ secrets.EMAIL_GOOGLE_USERNAME }} \
              -e EMAIL_GOOGLE_PASSWORD=${{ secrets.EMAIL_GOOGLE_PASSWORD }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -v /home/ec2-user/gcp-key.json:/app/gcp-key.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json \
              matteusmoreno/casa-moreno-backend:latest
            
            echo "Limpando o arquivo de credenciais do servidor EC2..."
            rm /home/ec2-user/gcp-key.json

            echo "Limpando imagens Docker antigas (dangling images)..."
            docker image prune -f || true
            
            echo "Verificando containers Docker em execução..."
            docker ps -a
            echo "Verificando logs do container recém-criado (pode demorar um pouco para aparecer)..."
            sleep 10
            docker logs casa-moreno-backend-container --tail 50