name: Deploy Backend to AWS ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  ECS_CLUSTER: casa-moreno-ec2-cluster                  # Nome do seu novo cluster
  ECS_SERVICE: casa-moreno-backend-service              # Nome do seu serviço de backend
  ECS_TASK_DEFINITION: backend-ec2-task                 # <--- MUDANÇA AQUI: O nome da sua task para EC2
  CONTAINER_NAME: casa-moreno-backend-container         # O nome do contêiner definido na sua Task Definition
  DOCKER_IMAGE: matteusmoreno/casa-moreno-backend:latest # O nome da sua imagem no Docker Hub

jobs:
  # Job 1: Builda a imagem Docker e envia para o Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

  # Job 2: Fazer o deploy no ECS
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download ECS Task Definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Clean task definition for deployment
        run: |
          jq 'del(.registeredAt, .registeredBy, .revision, .status, .taskDefinitionArn, .requiresAttributes, .compatibilities, .enableFaultInjection)' task-definition.json > task-definition-clean.json


      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition-clean.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.DOCKER_IMAGE }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true